# Generated by Django 4.0.10 on 2024-06-25 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('duration', models.PositiveSmallIntegerField(help_text='Average number of hours taken to finish the game.', null=True)),
                ('release_date', models.DateField(null=True)),
                ('in_early_access', models.BooleanField(default=False)),
                ('has_multiplayer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, max_length=1023, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
