# Generated by Django 4.0.10 on 2024-06-26 17:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gamerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('hours_played', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('percent_finished', models.DecimalField(decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100')), django.core.validators.MinValueValidator(Decimal('0'))])),
                ('played_with_friends', models.BooleanField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
