# Generated by Django 4.0.10 on 2024-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='rejected_at',
            field=models.DateTimeField(help_text='Date of the last rejection.', null=True),
        ),
        migrations.AddField(
            model_name='gamerequest',
            name='rejections',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of rejections.'),
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback regarding the reason(s) of last rejection.', max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='gamerequest',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Current status of the request.'),
        ),
    ]
